### ISSUE TITLE
RT5370 

### ISSUE THREAD

**Issue by Hiddenvirus-sohan** [rithvikvibhu/nh-magisk-wifi-firmware#53] opened 2020-08-01 16:49 UTC

**Comment by Hiddenvirus-sohan** [comment] 2020-08-01 16:50
Please add  this my adapter tenda w311m which supports monitor and packet injection on kali

**Comment by rithvikvibhu** [comment] 2020-10-31 03:56
Dupe of #50. Tracking in that issue, closing this as newer.

**Closed by rithvikvibhu** 2020-10-31 03:56 UTC
